name: Publish to PyPI
run-name: Publish to PyPI.
on:
  release:
    types: [released]
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/nb-unittest
    permissions:
      id-token: write 
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: |
          uv build && uv run --frozen make -C tests/
      - uses: pypa/gh-action-pypi-publish@release/v1
